# -*- coding: utf-8 -*-
"""Imagegeneration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1df9p9jqsiUAFQvhyVNvi426aLsdaW1JX

#Step 1: Install Required Libraries
"""

!pip install torch

!pip install diffusers

"""#Step 2: Load the Pre-trained *Model*"""

from diffusers import StableDiffusionPipeline
import torch

print("GPU Available:", torch.cuda.is_available())

# Only try to print device name if GPU is available
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

# Load the pre-trained Stable Diffusion model (in float32 for CPU)
pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    torch_dtype=torch.float32,        # changed from float16
    use_auth_token=True,              # if needed for gated model access
    revision="main"
)

pipe = pipe.to("cpu")  # CPU execution



"""#Step 3: Generate an Image"""

prompt = "A futuristic city skyline at sunset, with flying cars"
image = pipe(prompt).images[0]

# Show the generated image
image.show()

"""V2"""

from IPython.display import display

prompt = "A futuristic city skyline at sunset, with flying cars"
image = pipe(prompt).images[0]

# Show the generated image in Colab
display(image)

"""#Step 4: Image save"""

# Save the image locally
image.save("futuristic_city_skyline.png")

"""#futuristic_city_skyline.png"""

from PIL import Image as PILImage
from IPython.display import Image, display

# Save the image locally
filename = "futuristic_city_skyline.png"
image.save(filename)

# Display the saved image
display(Image(filename))

"""#A jellyfish floating through space"""

from IPython.display import display

prompt = "A jellyfish floating through space"
image = pipe(prompt).images[0]

# Show the generated image in Colab
display(image)

# Save the image locally
jellyfish = "jellyfish.png"
image.save(jellyfish)

# Display the saved image
display(Image(jellyfish))

"""#Dragon"""

from IPython.display import display

prompt = "A dragon soaring over a medieval castle during a lightning storm"
image = pipe(prompt).images[0]

# Show the generated image in Colab
display(image)

# Save the image locally
dragon = "dragon.png"
image.save(dragon)

"""#A peaceful lake with cherry blossom trees during spring"""

prompt = "A peaceful lake with cherry blossom trees during spring"
image = pipe(prompt).images[0]

# Show the generated image in Colab
display(image)

# Save the image locally
lake = "lake.png"
image.save(lake)

"""V2"""

prompt = "A peaceful lake with cherry blossom trees during spring"
image = pipe(prompt).images[0]

# Show the generated image in Colab
display(image)

# Save the image locally
lake = "lake.png"
image.save(lake)

"""# Why Use T4 GPU?
T4 supports float16 (half precision) and is optimized for inference workloads like Stable Diffusion.

You can use torch.float16 for better performance and memory efficiency.
"""

from diffusers import StableDiffusionPipeline
import torch

# Check GPU availability
print("GPU Available:", torch.cuda.is_available())

# Print GPU name if available
if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))

# Load the model using float16 for better GPU performance
pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    torch_dtype=torch.float16,            # Efficient half-precision for GPU
    use_auth_token=True,                  # Set this if needed
    revision="main"
)

# Move model to GPU
pipe = pipe.to("cuda")

# Prompt to generate image
prompt = "A fleet of alien spaceships approaching Earth"
image = pipe(prompt).images[0]

# Save and show image
image.save("futuristic_city_skyline.png")
image.show()

prompt = "A fleet of alien spaceships approaching Earth"
image = pipe(prompt).images[0]

# Show the generated image in Colab
display(image)

# Save the image locally
Alien = "Alien.png"
image.save(Alien)

prompt = "A fantasy forest glowing with bioluminescent plants and magical creatures"
image = pipe(prompt).images[0]

# Show the generated image in Colab
display(image)

# Save the image locally
Alien = "Alien.png"
image.save(Alien)



prompt = "A bmw car moving with rcket speed along with differnt creatures"
image = pipe(prompt).images[0]

# Show the generated image in Colab
display(image)

# Save the image locally
Alien = "Alien.png"
image.save(Alien)

from diffusers import StableDiffusionPipeline


import torch

torch.cuda.is_available()
torch.cuda.get_device_name(0)



